"""Add Speaker and SpeakerInvite tables

Revision ID: 23f5e5cea74
Revises: 9d4ba8cee
Create Date: 2016-02-07 16:06:58.273984

"""

# revision identifiers, used by Alembic.
import sqlalchemy_utils

from pygotham.talks.models import Speaker

revision = '23f5e5cea74'
down_revision = '9d4ba8cee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaker_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talk_id', sa.Integer(), nullable=False),
    sa.Column('invited_email', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['talk_id'], ['talks.id'], name=op.f('speaker_invites_talk_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('speaker_invites_pkey'))
    )
    op.create_table('speakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talk_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('primary', sa.Boolean(), nullable=False),
    sa.Column('recording_release', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('declined_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.ForeignKeyConstraint(['talk_id'], ['talks.id'], name=op.f('speakers_talk_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('speakers_user_id_fkey')),
    sa.Index('primary_user_for_talk', 'talk_id', 'user_id', unique=True, postgres_where=Speaker.primary == True),
    sa.PrimaryKeyConstraint('id', name=op.f('speakers_pkey'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speakers')
    op.drop_table('speaker_invites')
    ### end Alembic commands ###
