"""empty message

Revision ID: 27043d52abb
Revises: 5414cce8b09
Create Date: 2015-04-26 14:24:08.970161

"""

# revision identifiers, used by Alembic.
revision = '27043d52abb'
down_revision = '5414cce8b09'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
