"""create copresenter and add twitter handle

Revision ID: 4264aa7d921
Revises: 177a65486a0
Create Date: 2015-04-29 00:31:07.117520

"""

# revision identifiers, used by Alembic.
revision = '4264aa7d921'
down_revision = '177a65486a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copresenters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('twitter_handle', sa.String(length=255), nullable=True),
    sa.Column('talk_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['talk_id'], ['talks.id'], name=op.f('copresenters_talk_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('copresenters_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('copresenters_pkey'))
    )
    op.drop_column('talks', 'target_audience')
    op.drop_column('talks', 'abstract')
    op.drop_column('talks', 'objectives')
    op.drop_column('talks', 'outline')
    op.add_column('users', sa.Column('twitter_handle', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twitter_handle')
    op.add_column('talks', sa.Column('outline', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('talks', sa.Column('objectives', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('talks', sa.Column('abstract', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('talks', sa.Column('target_audience', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('copresenters')
    ### end Alembic commands ###
