"""Added speakers table

Revision ID: 4499b94e5e6
Revises: 9d4ba8cee
Create Date: 2016-02-01 19:57:47.945494

"""

# revision identifiers, used by Alembic.
import sqlalchemy_utils

revision = '4499b94e5e6'
down_revision = '9d4ba8cee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talk_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recording_release', sa.Boolean(), nullable=True),
    sa.Column('confirmed_ts', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('declined_ts', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.ForeignKeyConstraint(['talk_id'], ['talks.id'], name=op.f('speakers_talk_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('speakers_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('speakers_pkey'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speakers')
    ### end Alembic commands ###
