"""Added speaker_invites table

Revision ID: 492839e0f6a
Revises: 4499b94e5e6
Create Date: 2016-02-02 00:26:43.978999

"""

# revision identifiers, used by Alembic.
revision = '492839e0f6a'
down_revision = '4499b94e5e6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaker_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talk_id', sa.Integer(), nullable=False),
    sa.Column('claim_token', sa.String(length=255), nullable=False),
    sa.Column('invited_email', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['talk_id'], ['talks.id'], name=op.f('speaker_invites_talk_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('speaker_invites_pkey'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speaker_invites')
    ### end Alembic commands ###
