"""empty message

Revision ID: 5414cce8b09
Revises: c89e610ba4
Create Date: 2015-04-26 14:23:34.206766

"""

# revision identifiers, used by Alembic.
revision = '5414cce8b09'
down_revision = 'c89e610ba4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copresenters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('twitter_handle', sa.String(length=255), nullable=True),
    sa.Column('talk_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['talk_id'], ['talks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('talks', 'objectives')
    op.drop_column('talks', 'abstract')
    op.drop_column('talks', 'type')
    op.drop_column('talks', 'target_audience')
    op.drop_column('talks', 'outline')
    op.add_column('users', sa.Column('twitter_handle', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twitter_handle')
    op.add_column('talks', sa.Column('outline', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('talks', sa.Column('target_audience', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('talks', sa.Column('type', postgresql.ENUM('talk', 'tutorial', name='type'), autoincrement=False, nullable=False))
    op.add_column('talks', sa.Column('abstract', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('talks', sa.Column('objectives', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('copresenters')
    ### end Alembic commands ###
